version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${DB_NAME}                
      MYSQL_USER: ${DB_USER}                  
      MYSQL_PASSWORD: ${DB_PASSWORD}            
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express_be
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - DB_HOST=mysql-db                       
      - DB_USER=${DB_USER}                     
      - DB_PASSWORD=${DB_PASSWORD}           
      - DB_NAME=${DB_NAME}                     
      - PORT=${BACKEND_PORT}                    
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql-db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_fe
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mysql_data: